version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  branch:
    docker:
      - image: cimg/node:15.0
        auth:
          username: i2xzy
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
workflows:
  node-tests:
    jobs:
      - branch
